version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_pass
      POSTGRES_DB: dbt_demo
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  dbt:
    build: ./dbt
    container_name: dbt_runner
    depends_on:
      - postgres
    volumes:
      - ./dbt/dbt_project:/usr/app/dbt_project
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app/dbt_project
    command: >
      bash -c "dbt deps &&
               dbt seed &&
               dbt run &&
               tail -f /dev/null"

volumes:
  pg_data:
